name: Build and deploy examples to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build-examples:
    runs-on: ubuntu-latest
    if: github.repository == 'fairviewrobotics/2023-robot-code'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: 16
          cache: 'gradle'
      - uses: gradle/gradle-build-action@v2
      - name: Build html
        run: ./gradlew dokkaHtml --no-daemon --stacktrace
        working-directory: .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: source
          path: build/dokka

  deploy-examples:
    runs-on: ubuntu-latest
    needs: [ build-examples ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: source
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1
